apiVersion: v1
kind: Service
metadata:
  name:  section7-queuesvc
spec:
  selector:
    app: s7-activemq
    release: "1"
  
  ports:
  - name:  http
    port:  8161
    nodePort: 30010

  type: NodePort
  